# Generated by Django 4.0.4 on 2022-06-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
