# Generated by Django 4.0.4 on 2022-07-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogcomment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
    ]
