# Generated by Django 4.0.4 on 2022-05-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%y/%m/%d/', verbose_name='تصویر محصول'),
        ),
    ]
