# Generated by Django 4.0.4 on 2022-05-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_favorite_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='fullname',
            field=models.CharField(default='', max_length=500, verbose_name='نام کامل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='shop.product', verbose_name='محصول'),
        ),
    ]
