# Generated by Django 4.0.4 on 2022-05-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_item_options_alter_cart_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=18, verbose_name='قیمت'),
        ),
    ]
