# Generated by Django 4.0.4 on 2022-05-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('shop', '0012_remove_item_cart_remove_item_product_delete_cart_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductTag',
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, to='tag.tag'),
        ),
    ]
