# Generated by Django 4.0.4 on 2022-05-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد های خرید کاربران'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'ایتم های سبد های خرید مشتریان'},
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
